add canvas rendering integration example
no-chris/chord-symbol-demo pull request #1
Opened 2020-10-26 16:35 UTC by Marr11317

![image](https://user-images.githubusercontent.com/35939574/97199827-d914af00-1786-11eb-9bb3-b5e9a68a9277.png)

Also, I just installed npm v7, and it features a completely new package-lock format. So now the whole file appears as changed. I did not check it in because of that, so you'll have to run npm install to generate the new package-lock.json, but if you want, I can check in the file.

Also, I used the font Roboto in the canvas, because I had no idea what should use. Ideally, I'd use a true music font like [Petaluma Script](https://github.com/steinbergmedia/petaluma), but that would require additionnal font loading, so I didn't put it here. Do you think it's worth it?

2020-10-26 16:40 UTC, Marr11317 commented
sorry, first time with react: didn't know components had to be uppercased.

2020-10-26 16:42 UTC, Marr11317 commented
P.S: Here's the output with Petaluma Script
![image](https://user-images.githubusercontent.com/35939574/97201265-a10e6b80-1788-11eb-99dd-2ec853a2b917.png)

2020-10-26 21:54 UTC, no-chris commented
Wow! 😮 

How would the font loading work? Is it hosted somewhere like Google fonts or something? In anycase it looks so much better than I think it's worth the extra http call.

2020-10-27 05:05 UTC, Marr11317 commented
The font can be shipped with webpack. I haven't tried with third party services.
I'll check it out tomorrow.

2020-10-27 11:19 UTC, no-chris commented
I'm also concerned about browser compatibility and fallbacks? Not sure how this whole font things works

2020-10-27 17:54 UTC, Marr11317 commented
Looks pretty straightforward actually: https://webpack.js.org/guides/asset-management/#loading-fonts

2020-10-27 18:25 UTC, Marr11317 commented
oh, right, it's not webpack anymore

2020-10-27 19:32 UTC, Marr11317 commented
I followed this guide: https://medium.com/@sergeybulavyk/mastering-your-fonts-in-gatsby-fbdf2782e083
and used https://caniuse.com/?search=woff for browser compat

2020-10-27 19:33 UTC, Marr11317 commented
Would you rather have the second commit squashed into the first?

2020-10-27 19:47 UTC, Marr11317 commented
Also, I put both the woff and the woff2 file because the second is only a fraction of the size of the first, but the first has more cross-browser compat.

2020-10-27 20:03 UTC, Marr11317 commented
hmmm. For the first print, it is still the old font, since Petaluma Script isn't loaded yet (that happens asynchronously). But whenever the chord symbol changes, then it loads with the correct font.

2020-10-27 20:19 UTC, Marr11317 commented
> 
> 
> hmmm. For the first print, it is still the old font, since Petaluma Script isn't loaded yet (that happens asynchronously). But whenever the chord symbol changes, then it loads with the correct font.

fixed with adding `!important` in the css declaration. I don't see any additionnal lag.

2020-10-29 13:18 UTC, no-chris requested changes
Haven't tried it yet, sorry I have limited availability for a few days, will do my best

Any way the fonts files could be moved to : `src/components/showcase/CanvasRenderer/` along with all `CanvasRenderer` related files (.js, .scss)? If not possible, then I'd rather have them in `static/CanvasRenderer`.

The idea is to keep everything that works together in a single place.  Thanks!

2020-10-29 13:18 UTC, no-chris commented on scss/styles.scss
> +
Could you move this into `src/components/showcase/CanvasRenderer.scss` ?
You can then include the file directly from `src/components/showcase/CanvasRenderer.js` as with other components

2020-10-29 13:19 UTC, no-chris commented on scss/styles.scss
> +
Example of how to load the scss from a React component: https://github.com/no-chris/chord-symbol-demo/blob/25a4cf166ae0b30af4f752374fb113734ce7cbb9/src/components/ChordTable.js#L1

2020-10-29 19:39 UTC, Marr11317 commented
thanks for the review! I'll try to fix this as soon as possible, but have a some exams coming soon, so...

2020-10-29 22:25 UTC, no-chris commented
> thanks for the review! I'll try to fix this as soon as possible, but have a some exams coming soon, so...

Good luck then 😉

2020-10-30 08:04 UTC, no-chris commented
Hello
I cannot get it to work 😞 
I removed node modules and re-installed everything, ran gatsby clean and tried both a develop build and a production build, I cannot get the fonts to display, neither in Chrome or FF. My branch is up to date with the latest changes

<img width="1348" alt="Screenshot 2020-10-30 at 09 00 30" src="https://user-images.githubusercontent.com/11467480/97674983-bcca8800-1a8e-11eb-842b-f1d8eb4491ed.png">

Besides it seems that bb-text generates some console output that you might want to remove

2020-10-30 14:01 UTC, Marr11317 commented
so it really has something to do with the cache... ok, I'll check it as soo as possible.

2020-11-02 02:48 UTC, Marr11317 commented
ok, could you confirm it's fixed now? On first page loading, the font isn't available yet, since it's still being loaded, so it still shows the old font. However, if you change the chord symbol, it will redraw the canvas, using the then-downloaded font.

2020-11-02 02:52 UTC, Marr11317 commented
just removed the console output

2020-11-02 02:53 UTC, Marr11317 commented
> so it really has something to do with the cache... ok, I'll check it as soo as possible.

I had the font installed on my system, so it had nothing to do with the cache, but apparently the !important is not valid in a @font-face declaration, which resulted in it being invalid.

2020-11-02 02:59 UTC, Marr11317 commented
> On first page loading, the font isn't available yet, since it's still being downloaded, so it still shows the old font. however, whenever the canvas is redrawn, that is, whenever the chord symbol changes, the font is now available and is used.

That could probably be fixed with a library such as https://github.com/zachleat/fontfaceonload, but I wonder it is really necessary. Do you think it is?

2020-11-03 07:13 UTC, no-chris requested changes
Great job! 👏 

I'm fine to leave it like this for now if that's ok for you too.

Could you please make sure that prettier rules are applied? I messed around locally with your file and it seems that some re-formatting was triggered.
`npm run-script format`

2020-11-03 07:13 UTC, no-chris commented on src/components/showcase/CanvasRenderer/CanvasRenderer.js
> +
For better consistency with the rest of the codebase could you please try to refactor as follow:
- extract CanvasComponent to its own file and pass it `renderedChordRaw` as a prop
- move the `draw` function declaration to this component since it does not need to be declared in the parent component (unless I missed something)

2020-11-03 07:13 UTC, no-chris commented on src/components/showcase/CanvasRenderer/CanvasRenderer.js
> +    }, [draw]);
when proceeding with the refactor this should probably be replaced by `renderedChordRaw`, which would only trigger the re-render if `renderedChordRaw` changes.
```javascript
useEffect(() => { ... }, [renderedChordRaw]);
```

2020-11-03 18:13 UTC, Marr11317 commented
`npm run format` fixed a lot of files I didn't touch. It seems that it fixed the file endings. I just committed the files related to this PR.

2020-11-04 17:44 UTC, no-chris approved these changes

2020-11-04 17:45 UTC, merged